# Generated by Django 5.0.2 on 2024-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('course_lecturer', models.CharField(max_length=40)),
                ('no_of_units', models.IntegerField()),
                ('department', models.CharField(max_length=40)),
            ],
        ),
    ]
